collections:
  category_pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "category_pages"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"